name: Build Game Executables

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            pyinstaller_separator: ":"
          - os: macos-latest
            pyinstaller_separator: ":"
          - os: windows-latest
            pyinstaller_separator: ";"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # FIX 1: Changed to a more stable Python version with full package support.
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Install System Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf
      
    - name: Install/Upgrade Setuptools
      run: python -m pip install --upgrade pip setuptools

    # FIX 2: Corrected pyinstaller version to an existing one.
    - name: Install Python packages
      run: python -m pip install pygame==2.6.0 platformdirs==4.2.2 pyinstaller==6.8.0

    - name: Build with PyInstaller
      run: pyinstaller --onefile --add-data "assets${{ matrix.pyinstaller_separator }}assets" --name gothic-rogue main.py

    - name: Stage Artifact
      shell: bash
      run: |
        mkdir build
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv ./dist/gothic-rogue.exe ./build/
        else
          mv ./dist/gothic-rogue ./build/
        fi

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gothic-rogue-${{ matrix.os }} 
        path: ./build/*

